export const adminAreas = [
  ['products', 'Products', 'المنتجات', 'catalog.write'],
  ['categories', 'Categories', 'الفئات', 'catalog.write'],
  ['brands', 'Brands', 'العلامات التجارية', 'catalog.write'],
  ['motorcycles', 'Motorcycles', 'الدراجات', 'motorcycles.write'],
  ['fitment', 'Fitment', 'التوافق', 'catalog.write'],
  ['branches', 'Branches', 'الفروع', 'motorcycles.write'],
  ['orders', 'Orders', 'الطلبات', 'orders.read'],
  ['reservations', 'Reservations', 'الحجوزات', 'reservations.read'],
  ['customers', 'Customers', 'العملاء', 'customers.read'],
  ['inventory', 'Inventory', 'المخزون', 'inventory.write'],
  ['suppliers', 'Suppliers', 'الموردون', 'inventory.write'],
  ['reviews', 'Reviews', 'التقييمات', 'content.write'],
  ['audit', 'Audit logs', 'سجل التدقيق', 'audit.read'],
  ['promotions', 'Promotions', 'العروض', 'catalog.write'],
  ['returns', 'Returns', 'المرتجعات', 'orders.read'],
  ['warranties', 'Warranties', 'الضمانات', 'orders.read'],
  ['staff', 'Staff & roles', 'الموظفون والصلاحيات', 'staff.write'],
  ['settings', 'Store settings', 'إعدادات المتجر', 'settings.write'],
  ['reports', 'Reports', 'التقارير', 'reports.read'],
] as const;
