create table public.warehouses(id uuid primary key default gen_random_uuid(), name text not null, branch_id uuid references public.branches, active boolean not null default true);
create table public.inventory(id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products, variant_id uuid references public.product_variants, warehouse_id uuid not null references public.warehouses, on_hand int not null default 0 check(on_hand>=0), reserved int not null default 0 check(reserved>=0 and reserved<=on_hand), incoming int not null default 0 check(incoming>=0), unique nulls not distinct(product_id,variant_id,warehouse_id));
create table public.inventory_movements(id uuid primary key default gen_random_uuid(), inventory_id uuid not null references public.inventory, delta int not null check(delta<>0), reason text not null, actor_id uuid not null references auth.users, created_at timestamptz not null default now());
create table public.suppliers(id uuid primary key default gen_random_uuid(), name text not null, contact_name text, email text, phone text, notes text, active boolean not null default true);
create table public.supplier_products(supplier_id uuid not null references public.suppliers on delete cascade, product_id uuid not null references public.products on delete cascade, supplier_sku text, cost_egp numeric(12,2) check(cost_egp>=0), primary key(supplier_id,product_id));
create table public.purchase_orders(id uuid primary key default gen_random_uuid(), supplier_id uuid not null references public.suppliers, status text not null default 'draft' check(status in ('draft','placed','partially_received','received','cancelled')), created_by uuid references auth.users, created_at timestamptz not null default now());
create table public.purchase_order_items(id uuid primary key default gen_random_uuid(), purchase_order_id uuid not null references public.purchase_orders on delete cascade, product_id uuid not null references public.products, quantity int not null check(quantity>0), received_quantity int not null default 0 check(received_quantity>=0 and received_quantity<=quantity), unit_cost_egp numeric(12,2) not null check(unit_cost_egp>=0));
create table public.promotions(id uuid primary key default gen_random_uuid(), code text unique, name text not null, type text not null check(type in ('percent','fixed')), value numeric(12,2) not null check(value>0), min_total_egp numeric(12,2) not null default 0, usage_limit int, per_customer_limit int, starts_at timestamptz not null, ends_at timestamptz not null check(ends_at>starts_at), active boolean not null default true, check(type<>'percent' or value<=100));
create table public.promotion_targets(promotion_id uuid not null references public.promotions on delete cascade, product_id uuid references public.products, category_id uuid references public.categories, brand_id uuid references public.brands, check(num_nonnulls(product_id,category_id,brand_id)=1));
create table public.coupon_usage(id uuid primary key default gen_random_uuid(), promotion_id uuid not null references public.promotions, user_id uuid not null references auth.users, order_id uuid not null references public.orders, used_at timestamptz not null default now(), unique(promotion_id,order_id));
create table public.return_requests(id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders, user_id uuid not null references auth.users, reason text not null, status text not null default 'requested' check(status in ('requested','approved','rejected','received','inspected','refunded','completed')), created_at timestamptz not null default now());
create table public.return_items(return_id uuid not null references public.return_requests on delete cascade, order_item_id uuid not null references public.order_items, quantity int not null check(quantity>0), primary key(return_id,order_item_id));
create table public.warranties(id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users, order_item_id uuid not null references public.order_items, serial_number text, starts_at date not null, ends_at date not null check(ends_at>=starts_at), status text not null default 'active' check(status in ('active','expired','void')));
create table public.warranty_claims(id uuid primary key default gen_random_uuid(), warranty_id uuid not null references public.warranties, user_id uuid not null references auth.users, details text not null, status text not null default 'requested' check(status in ('requested','reviewing','approved','rejected','completed')), created_at timestamptz not null default now());
create table public.invoices(id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders, invoice_number bigint generated always as identity unique, snapshot jsonb not null, created_at timestamptz not null default now());
create table public.site_settings(key text primary key, value jsonb not null, updated_at timestamptz not null default now());
create index inventory_product_idx on public.inventory(product_id);create index movements_inventory_idx on public.inventory_movements(inventory_id,created_at desc);create index supplier_products_product_idx on public.supplier_products(product_id);create index returns_user_idx on public.return_requests(user_id);create index warranty_user_idx on public.warranties(user_id);
do $$declare t text;begin foreach t in array array['warehouses','inventory','inventory_movements','suppliers','supplier_products','purchase_orders','purchase_order_items','promotions','promotion_targets','coupon_usage','return_requests','return_items','warranties','warranty_claims','invoices','site_settings'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;

create policy brands_staff_insert on public.brands for insert to authenticated with check(public.has_permission('catalog.write'));
create policy brands_staff_update on public.brands for update to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy categories_staff_insert on public.categories for insert to authenticated with check(public.has_permission('catalog.write'));
create policy categories_staff_update on public.categories for update to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy products_staff_select on public.products for select to authenticated using(public.has_permission('catalog.write'));
create policy products_staff_insert on public.products for insert to authenticated with check(public.has_permission('catalog.write'));
create policy products_staff_update on public.products for update to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy variants_staff_all on public.product_variants for all to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy product_images_staff_all on public.product_images for all to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy motorcycles_staff_select on public.motorcycles for select to authenticated using(public.has_permission('motorcycles.write'));
create policy motorcycles_staff_insert on public.motorcycles for insert to authenticated with check(public.has_permission('motorcycles.write'));
create policy motorcycles_staff_update on public.motorcycles for update to authenticated using(public.has_permission('motorcycles.write')) with check(public.has_permission('motorcycles.write'));
create policy used_details_staff_all on public.used_motorcycle_details for all to authenticated using(public.has_permission('motorcycles.write')) with check(public.has_permission('motorcycles.write'));
create policy motorcycle_images_staff_all on public.motorcycle_images for all to authenticated using(public.has_permission('motorcycles.write')) with check(public.has_permission('motorcycles.write'));
create policy fitment_staff_all on public.fitment_rules for all to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy staff_roles_write on public.staff_roles for all to authenticated using(public.has_permission('staff.write')) with check(public.has_permission('staff.write'));
create policy orders_staff_update on public.orders for update to authenticated using(public.has_permission('orders.write')) with check(public.has_permission('orders.write'));
create policy reservations_staff_update on public.motorcycle_reservations for update to authenticated using(public.has_permission('reservations.write')) with check(public.has_permission('reservations.write'));
create policy reviews_moderate on public.reviews for update to authenticated using(public.has_permission('content.write')) with check(public.has_permission('content.write'));
create policy warehouses_staff on public.warehouses for all to authenticated using(public.has_permission('inventory.write')) with check(public.has_permission('inventory.write'));
create policy inventory_staff on public.inventory for select to authenticated using(public.has_permission('inventory.write'));
create policy movements_staff on public.inventory_movements for select to authenticated using(public.has_permission('inventory.write'));
create policy suppliers_staff on public.suppliers for all to authenticated using(public.has_permission('inventory.write')) with check(public.has_permission('inventory.write'));
create policy supplier_products_staff on public.supplier_products for all to authenticated using(public.has_permission('inventory.write')) with check(public.has_permission('inventory.write'));
create policy po_staff on public.purchase_orders for all to authenticated using(public.has_permission('inventory.write')) with check(public.has_permission('inventory.write'));
create policy po_items_staff on public.purchase_order_items for all to authenticated using(public.has_permission('inventory.write')) with check(public.has_permission('inventory.write'));
create policy promotions_public on public.promotions for select to anon,authenticated using(active and now() between starts_at and ends_at);
create policy promotions_staff on public.promotions for all to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy promotion_targets_staff on public.promotion_targets for all to authenticated using(public.has_permission('catalog.write')) with check(public.has_permission('catalog.write'));
create policy returns_own on public.return_requests for select to authenticated using(user_id=auth.uid() or public.has_permission('orders.read'));
create policy return_items_own on public.return_items for select to authenticated using(exists(select 1 from public.return_requests r where r.id=return_id and (r.user_id=auth.uid() or public.has_permission('orders.read'))));
create policy warranties_own on public.warranties for select to authenticated using(user_id=auth.uid() or public.has_permission('orders.read'));
create policy claims_own on public.warranty_claims for select to authenticated using(user_id=auth.uid() or public.has_permission('orders.read'));
create policy invoices_own on public.invoices for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.has_permission('orders.read'))));
create policy settings_staff on public.site_settings for all to authenticated using(public.has_permission('staff.write')) with check(public.has_permission('staff.write'));
create policy notification_read_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

create function public.adjust_inventory(p_inventory uuid,p_delta int,p_reason text) returns void language plpgsql security definer set search_path=public as $$declare v_before int;v_after int;begin
  if not public.has_permission('inventory.write') then raise exception 'Forbidden';end if;
  if p_delta=0 or length(trim(p_reason))<5 then raise exception 'Invalid adjustment';end if;
  select on_hand into v_before from public.inventory where id=p_inventory for update;
  if v_before is null then raise exception 'Inventory not found';end if;
  v_after:=v_before+p_delta;
  if v_after<0 or v_after<(select reserved from public.inventory where id=p_inventory) then raise exception 'Insufficient stock';end if;
  update public.inventory set on_hand=v_after where id=p_inventory;
  insert into public.inventory_movements(inventory_id,delta,reason,actor_id) values(p_inventory,p_delta,p_reason,auth.uid());
  insert into public.audit_logs(actor_id,action,entity,entity_id,detail) values(auth.uid(),'inventory.adjust','inventory',p_inventory,jsonb_build_object('before',v_before,'after',v_after,'reason',p_reason));
end$$;
revoke all on function public.adjust_inventory(uuid,int,text) from public;
grant execute on function public.adjust_inventory(uuid,int,text) to authenticated;

create function public.audit_change() returns trigger language plpgsql security definer set search_path=public as $$begin
  insert into public.audit_logs(actor_id,action,entity,entity_id,detail) values(auth.uid(),tg_op,lower(tg_table_name),coalesce(new.id,old.id),jsonb_build_object('old',to_jsonb(old),'new',to_jsonb(new)));
  return coalesce(new,old);
end$$;
create trigger audit_products after insert or update or delete on public.products for each row execute function public.audit_change();
create trigger audit_motorcycles after insert or update or delete on public.motorcycles for each row execute function public.audit_change();
create trigger audit_reservations after update on public.motorcycle_reservations for each row execute function public.audit_change();
create function public.enforce_paid_status() returns trigger language plpgsql security definer set search_path=public as $$begin
  if tg_table_name='orders' and new.status in ('paid','processing','shipped','delivered') and not exists(select 1 from public.payments where order_id=new.id and status='captured' and amount_egp>=new.total_egp) then raise exception 'Verified captured payment required';end if;
  if tg_table_name='motorcycle_reservations' and new.status in ('deposit_paid','contacted','appointment_scheduled','completed') and not exists(select 1 from public.payments where reservation_id=new.id and status='captured' and amount_egp>=new.deposit_egp) then raise exception 'Verified deposit required';end if;
  return new;
end$$;
create trigger enforce_order_paid before update of status on public.orders for each row execute function public.enforce_paid_status();
create trigger enforce_reservation_paid before update of status on public.motorcycle_reservations for each row execute function public.enforce_paid_status();
